### ISSUE TITLE
Mobile phone error

### ISSUE THREAD

**Issue by marioscovazzi** [open-education-polito/fare-platform#136]
with the mobile phone the user menu fields are not visible

**Comment by CorsoGabriele** [comment]
The menu icon is present in the top right corner, and if clicked the menu appears. In any case a smartphone app would be more suitable for mobile usage
![Screenshot from 2020-08-07 18-21-17](https://user-images.githubusercontent.com/26136821/89667352-488fa680-d8dc-11ea-8e29-f060a6e065d6.png)
