### ISSUE TITLE
Select color palette 

### ISSUE THREAD

**Issue by libremente** [open-education-polito/fare-platform#162]
## Expected Behavior
There should be a defined color palette for the UI

## Actual Behavior
There are too many colors, this is not good for accessibility and general navigation.
We should pick a color palette and stick to it.

**Comment by libremente** [comment]
We could try this one: https://coolors.co/

**Comment by EugenioCorso** [comment]
Thanks for the link! I think that [this](https://coolors.co/f0edee-b3cde0-6497b1-005b96-335b7e) should fit
