### ISSUE TITLE
Plan backup strategy

### ISSUE THREAD

**Issue by libremente** [open-education-polito/fare-platform#178]
## Expected Behavior
We should have a solid backup strategy

@EugenioCorso @CorsoGabriele since we will be using named volumes, please check something like this 
https://medium.com/@loomchild/backup-restore-docker-named-volumes-350397b8e362

Also, please document all the strategy: active dumps, TARs of the volumes etc.

**Comment by CorsoGabriele** [comment]
I have already done a first vesion, different from the one suggested in the link. Check the commit [here](https://github.com/open-education-polito/fare-platform/commit/7d5e6c7be7acd3f2ec72a86649eb4b365c9139b6) and the its documentation [here](https://github.com/open-education-polito/fare-platform/commit/28c34ade856d10d9ba7d0f1b4bb95d3bf504af41)
