### ISSUE TITLE
Implement logging system

### ISSUE THREAD

**Issue by libremente** [open-education-polito/fare-platform#51]
It is necessary to implement a robust logging system.
Such a system must have:
* timestamps
* different verbosity levels
* easy to be parsed

Please check how logging is handled inside Invenio (I believe they use a mix of Flask / Python logging engines).

**Comment by libremente** [comment]
Add mapping in dockerfile for the var folder. It should be on the machine and not on the docker container.

**Comment by libremente** [comment]
This is linked to #75

**Comment by EugenioCorso** [comment]
The logging system was implemented in 688dedd and the relative PR (#68) closed, so we can close this issue as well
