### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by EugenioCorso** [open-education-polito/fare-platform#73]
Running the test script occur this error message:
```
Checking PEP 508 requirements…
Passed!
Checking installed package safety…
An error occurred:
Your API Key '1ab8d58f-5122e025-83674263-bc1e79e0' is invalid. See https://goo.gl/O7Y1rS
```

**Comment by libremente** [comment]
It's definitely this case https://github.com/pypa/pipenv/issues/4188
@EugenioCorso could you please go through such an issue an try to propose a solution (if there's already one)? Thanks!

**Comment by libremente** [comment]
Direi che questa si risolve così: https://github.com/pypa/pipenv/issues/4188#issuecomment-614877929
Puoi provare e confermare @EugenioCorso? Grazie

**Comment by EugenioCorso** [comment]
@libremente I tried and it works!

**Comment by EugenioCorso** [comment]
Removed `.env` file because no longer needed, the issue was solved [here](https://github.com/pypa/pipenv/issues/4188#issuecomment-614877929)
