### ISSUE TITLE
Port kibana to newer version in docker-compose

### ISSUE THREAD

**Issue by libremente** [open-education-polito/fare-platform#81]
## Expected Behavior
The Kibana service should be at its latest version.
Please update and check the compatibility

## Actual Behavior
It is fixed to 6.6.2

## Steps to Reproduce the Problem
Check the docker-compose and services files

**Comment by EugenioCorso** [comment]
The latest Kibana version is the 7.6.2 but we need the latest version compatible with our ES 7.2.0 that is Kibana 7.2.1. The port was made in this commit 17d5a50a2e8c619650580448f5032d64bb10b6a2

**Comment by libremente** [comment]
Cool, since you have to rebase against master you could probably also rename the commit into "fix #81 bla bla" so we handle the closure automatically. Thanks!
