### ISSUE TITLE
Add AUTHORS names

### ISSUE THREAD

**Issue by libremente** [open-education-polito/fare-platform#84]
@CorsoGabriele @EugenioCorso you should add your names in the AUTHORS file.

**Comment by libremente** [comment]
Please let's proceed in the following way:
* Open an issue
* Open a PR referencing that issue in the body text
* Fix the issue in a commit quoting "Add authors names, fix #84" or something similar
* When the PR is merged, close the issue (automatically or manually).
Thanks @EugenioCorso @CorsoGabriele

**Comment by CorsoGabriele** [comment]
I will change the commit message

**Comment by libremente** [comment]
Fixed in https://github.com/open-education-polito/fare-platform/commit/d68a3cd4bc7a8a806a7652bb542827c40b959e31
