### ISSUE TITLE
Insert loader to provide upload progress feedback

### ISSUE THREAD

**Issue by libremente** [open-education-polito/fare-platform#91]
## Expected Behavior
The file loading process should provide information regarding the status of the process. 

## Actual Behavior
Nothing happens, so the user is somehow lost and does not know how to proceed.

## Steps to Reproduce the Problem
Upload a file.

**Comment by EugenioCorso** [comment]
The view was enhanced at this commit 71bb7e052105e8999f055b0b62315d004929f2fd to guide the user and provide a better UX
